### ISSUE TITLE
最初のエピック

### ISSUE THREAD

**Issue by gouf** [gouf/url_mind#1]
# 目的・問題

* デスクトップにWeb ブラウザのタブがたくさん開かれてて、目移りして 目の前のことに集中できない
* 既存の「後で読む」だと、保持しているURL が「沢山あるように見える場合」に、余計な先読みが走って「コレも読まなきゃ アレも読まなきゃ」と面倒くさくなって行動に起こしづらい

# 進め方

今回は最初の機能として、盛り沢山にはせず、一歩ずつ進めていく
今後も、実装すると決めた機能が多いと少しでも感じたら「次にやってみたいこと」に後回しにする

# 仕様

## サーバ

とりあえず Heroku に建てる

### アクション

* [x] index (GET) : 今回ではまだ一覧表示のみ(次回以降カテゴリごとにグループ分けした状態で一覧表示させる)
* [x] push (POST) : 文字列を受け取り、データベースに記録する(URL encoded なURL を想定)
* [x] pop (GET) : データベースからURL 群のレコードを **ID の若い順** で1つ受け取り、返す。その1つは削除する。

#### データベース

* Readlaters テーブルを作成する

##### テーブル内容(カラム構成)

* ID (PRIAMRY KEY, auto increment)
* url (string)

### クライアント

_特になし_

# 次にやってみたいこと
「多ければさらに後回し」を忘れないこと

* レコードに対してカテゴリ付けしたい(ドメイン名で雑に分類)
* 「今日の GitHub のピックアップはこれ」; 読む対象カテゴリを集中的な選択を可能にする
* 統計情報の表示? 「今週はこれだけの後で読むを消化しました」機能
