### ISSUE TITLE
今週の機能追加(2018/03/12 ~ 2018/03/17)

### ISSUE THREAD

**Issue by gouf** [gouf/url_mind#8]
# 機能追加・変更

* [x] Markdown のリスト形式でURL をコピペしたら、URL 部分だけを抜き出して後で読むリストにレコードとして保存する
* [x] Web ブラウザ側から、後で読むリストのURL をひとつ呼び出して 別タブないし別ウィンドウとして表示させる : #13 
* [x] Rubocop のTargetRubyVersion を `2.5.0` に設定する : #10 
* [x] プライベートユース目的でHeroku にデプロイする : #11
* [x] 本リポジトリを起点にHeroku にデプロイできるようにする(Deploy to Heroku Button の設置 : [Creating a 'Deploy to Heroku' Button | Heroku Dev Center](https://devcenter.heroku.com/articles/heroku-button)) : #12 

## 引き継ぎ

前回(#1) からの引き継ぎ

* レコードに対してカテゴリ付けしたい(ドメイン名で雑に分類)
* 「今日の GitHub のピックアップはこれ」; 読む対象カテゴリを集中的な選択を可能にする
* 統計情報の表示? 「今週はこれだけの後で読むを消化しました」機能

「多かったら後回し」を忘れずに!!

# リポジトリのメンテナンス

* [x] ZenHub 導入していることを明示 : #14 
* [x] Rubocop 導入していることを明示 : #22
* [x] Deploy to Heroku ボタンの設置 : #12

**Comment by gouf** [comment]
2018/03/12 ~ 2018/03/17 の間で、42 ポイントの issue, Pull Request を対応できた

これから v0.1.0 のリリース作業に移行する

**Comment by gouf** [comment]
Done. 💪
